### ISSUE TITLE
not able to build for resolve 11

### ISSUE THREAD

**Issue by mikewoodworth** [devernay/openfx-yadif#2]
I'm building with the Xcode project file, I can't get it to load in Resolve without crashing the app. I'm not finding any useful logs in console to help debug. Any ideas?

Resolve 11.1.3
OSX 10.10.1
xcode 6.1.1

**Comment by MarcusWolschon** [comment]
I have the same issue. 
Color tab works, as is rendering the first 1-20 frames. Then resolve crashes.
Is there any log to look at for finding the cause?
